# Generated by Django 4.0 on 2022-01-03 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahc_repositories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='repository',
            name='slug',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='repository',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='upstream',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='repository',
            name='upstream_type',
            field=models.CharField(choices=[('G', 'Git')], max_length=1),
        ),
        migrations.AlterField(
            model_name='repositoryenvvariable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='repositoryenvvariable',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='repositoryenvvariable',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_variables', to='ahc_repositories.repository'),
        ),
        migrations.AlterField(
            model_name='repositoryenvvariable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='repositoryenvvariable',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='repositoryuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='repositoryuser',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='ahc_repositories.repository'),
        ),
        migrations.AlterField(
            model_name='repositoryuser',
            name='type',
            field=models.CharField(choices=[('O', 'Owner'), ('C', 'Collaborator')], max_length=1),
        ),
        migrations.AlterField(
            model_name='repositoryuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
