image: docker:latest

stages:
  # - build
  # - test
  - deploy

variables:
  RULES_CHANGES_PATH: "**/*"

.backend:
  variables:
    RULES_CHANGES_PATH: "ahc_backend/**/*"

.frontend:
  variables:
    RULES_CHANGES_PATH: "ahc_frontend/**/*"

.runner:
  variables:
    RULES_CHANGES_PATH: "ahc_runner/**/*"

before_script:
  - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASS $DOCKER_REGISTRY

backend-deploy-dev:
  stage: deploy
  extends: .backend
  script:
    - export DOCKER_TAG=${CI_COMMIT_SHA::8}-$(date +%s)
    - export DOCKER_IMAGE=$DOCKER_REGISTRY/$DOCKER_REGISTRY_USER/backend

    - docker build --pull --cache-from $DOCKER_IMAGE:dev --tag $DOCKER_IMAGE:dev ahc_backend
    - docker tag $DOCKER_IMAGE:dev $DOCKER_IMAGE:$DOCKER_TAG
    - docker push $DOCKER_IMAGE:dev
    - docker push $DOCKER_IMAGE:$DOCKER_TAG

  only:
    - development

frontend-deploy-dev:
  stage: deploy
  extends: .frontend
  script:
    - export DOCKER_TAG=${CI_COMMIT_SHA::8}-$(date +%s)
    - export DOCKER_IMAGE=$DOCKER_REGISTRY/$DOCKER_REGISTRY_USER/frontend

    - docker build --pull --cache-from $DOCKER_IMAGE:dev --tag $DOCKER_IMAGE:dev ahc_frontend
    - docker tag $DOCKER_IMAGE:dev $DOCKER_IMAGE:$DOCKER_TAG
    - docker push $DOCKER_IMAGE:dev
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  only:
    - development

runner-deploy-dev:
  stage: deploy
  extends: .runner
  script:
    - export DOCKER_TAG=${CI_COMMIT_SHA::8}-$(date +%s)
    - export DOCKER_IMAGE=$DOCKER_REGISTRY/$DOCKER_REGISTRY_USER/frontend

    - docker build --pull --cache-from $DOCKER_IMAGE:dev --tag $DOCKER_IMAGE:dev ahc_frontend
    - docker tag $DOCKER_IMAGE:dev $DOCKER_IMAGE:$DOCKER_TAG
    - docker push $DOCKER_IMAGE:dev
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  only:
    - development
