# Generated by Django 4.0 on 2022-04-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahc_runners', '0004_alter_runnerjob_experiment_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerjob',
            name='is_success',
            field=models.BooleanField(default=True),
        ),
    ]
