# Generated by Django 4.0 on 2022-04-13 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ahc_runners', '0005_runnerjob_is_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerjob',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='auth.user'),
        ),
    ]
