# Generated by Django 4.0 on 2022-04-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahc_runners', '0006_runnerjob_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runnerjob',
            options={'ordering': ('-priority', '-created_at')},
        ),
        migrations.AddField(
            model_name='runnerjob',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
