# Generated by Django 4.0 on 2022-04-26 11:29

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ahc_runners', '0007_alter_runnerjob_options_runnerjob_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runnerjob',
            options={'ordering': ('is_finished', 'is_running', '-priority', 'created_at')},
        ),
        migrations.AlterModelManagers(
            name='runnerjob',
            managers=[
                ('ranked_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
