version: "3"

services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ahc
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    restart: always

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: always
