version: "3"

services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ahc
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    restart: always

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    volumes:
      - /data
    restart: always

  minio:
    image: minio/minio
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ahc # AWS_S3_ACCESS_KEY_ID
      MINIO_ROOT_PASSWORD: ahc # AWS_S3_SECRET_ACCESS_KEY
    volumes:
      - /data
    restart: always
