version: "3"

services:
  app:
    build: .
    command: |
      /bin/sh -c "
        ./docker-wait-for-it.sh -h postgres -t 0 -p 5432 &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - mediafiles:/app/media
    restart: always

  postgres:
    image: postgres:13-alpine
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: ahc
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    restart: always

  redis:
    image: redis:6-alpine
    restart: always

volumes:
  mediafiles: {}
