# Generated by Django 3.2.9 on 2021-11-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahc_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
