# Generated by Django 4.0 on 2022-01-04 19:44

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('ahc_users', '0005_userprofile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=''),
        ),
    ]
