# Generated by Django 4.0 on 2022-04-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahc_users', '0007_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
