name: Run build

on:
  push:
    branches:
      - main

jobs:
  backend_build:
    name: Build backend
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: git checkout
        uses: actions/checkout@v3

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ahc_backend
          tags: ghcr.io/cengwins/ahc-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  frontend_build:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: git checkout
        uses: actions/checkout@v3

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ahc_frontend
          tags: ghcr.io/cengwins/ahc-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            SERVER_URL=https://ahc.ceng.metu.edu.tr/api/

  runner_build:
    name: Build runner
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: git checkout
        uses: actions/checkout@v3

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ahc_runner
          tags: ghcr.io/cengwins/ahc-runner:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
